# shellcheck shell=bash
# gh-flag-table.sh — GENERATED by ai/bin/cli-flag-table from gh 2.96.0. Do not
# edit by hand: after a gh upgrade, run `ai/bin/cli-flag-table --cli gh --write`.
# Sourced by ai/lib/gh-outbound-scan.sh (DND-1976), never run.
#
# GFT_FLAGS[<command>] holds one entry per flag, <kind>:<short>:<long>:
#   v  takes a value: pflag gives it the next word, even one starting with -
#   b  takes none: a switch, set by its name alone (or --name=value)
# GFT_ALIAS[<alias>] is the command it names.
GFT_VERSION='2.96.0'
declare -gA GFT_FLAGS=(
  ['issue close']=' v:c:comment v::duplicate-of v:r:reason b::help v:R:repo '
  ['issue comment']=' v:b:body v:F:body-file b::create-if-none b::delete-last b::edit-last b:e:editor b:w:web b::yes b::help v:R:repo '
  ['issue create']=' v:a:assignee v::blocked-by v::blocking v:b:body v:F:body-file b:e:editor v:l:label v:m:milestone v::parent v:p:project v::recover v:T:template v:t:title v::type b:w:web b::help v:R:repo '
  ['issue edit']=' v::add-assignee v::add-blocked-by v::add-blocking v::add-label v::add-project v::add-sub-issue v:b:body v:F:body-file v:m:milestone v::parent v::remove-assignee v::remove-blocked-by v::remove-blocking v::remove-label b::remove-milestone b::remove-parent v::remove-project v::remove-sub-issue b::remove-type v:t:title v::type b::help v:R:repo '
  ['issue reopen']=' v:c:comment b::help v:R:repo '
  ['pr close']=' v:c:comment b:d:delete-branch b::help v:R:repo '
  ['pr comment']=' v:b:body v:F:body-file b::create-if-none b::delete-last b::edit-last b:e:editor b:w:web b::yes b::help v:R:repo '
  ['pr create']=' v:a:assignee v:B:base v:b:body v:F:body-file b:d:draft b::dry-run b:e:editor b:f:fill b::fill-first b::fill-verbose v:H:head v:l:label v:m:milestone b::no-maintainer-edit v:p:project v::recover v:r:reviewer v:T:template v:t:title b:w:web b::help v:R:repo '
  ['pr edit']=' v::add-assignee v::add-label v::add-project v::add-reviewer v:B:base v:b:body v:F:body-file v:m:milestone v::remove-assignee v::remove-label b::remove-milestone v::remove-project v::remove-reviewer v:t:title b::help v:R:repo '
  ['pr merge']=' b::admin v:A:author-email b::auto v:b:body v:F:body-file b:d:delete-branch b::disable-auto v::match-head-commit b:m:merge b:r:rebase b:s:squash v:t:subject b::help v:R:repo '
  ['pr reopen']=' v:c:comment b::help v:R:repo '
  ['pr review']=' b:a:approve v:b:body v:F:body-file b:c:comment b:r:request-changes b::help v:R:repo '
  ['release create']=' v::discussion-category b:d:draft b::fail-on-no-commits b::generate-notes b::latest v:n:notes v:F:notes-file b::notes-from-tag v::notes-start-tag b:p:prerelease v::target v:t:title b::verify-tag b::help v:R:repo '
  ['release edit']=' v::discussion-category b::draft b::latest v:n:notes v:F:notes-file b::prerelease v::tag v::target v:t:title b::verify-tag b::help v:R:repo '
)
declare -gA GFT_ALIAS=(
  ['issue new']='issue create'
  ['pr new']='pr create'
  ['release new']='release create'
)
