# shellcheck shell=bash
# glab-flag-table.sh — GENERATED by ai/bin/cli-flag-table from glab 1.92.1. Do not
# edit by hand: after a glab upgrade, run `ai/bin/cli-flag-table --cli glab --write`.
# Sourced by ai/lib/glab-outbound-scan.sh (DND-1976), never run.
#
# LFT_FLAGS[<command>] holds one entry per flag, <kind>:<short>:<long>:
#   v  takes a value: pflag gives it the next word, even one starting with -
#   b  takes none: a switch, set by its name alone (or --name=value)
# LFT_ALIAS[<alias>] is the command it names.
LFT_VERSION='1.92.1'
declare -gA LFT_FLAGS=(
  ['incident note']=' b:h:help v:m:message v:R:repo '
  ['issue create']=' v:a:assignee b:c:confidential v:d:description v::due-date v::epic b:h:help v:l:label v::link-type v::linked-issues v::linked-mr v:m:milestone b::no-editor b::recover v:R:repo v:e:time-estimate v:s:time-spent v:t:title b::web v:w:weight b:y:yes '
  ['issue note']=' b:h:help v:m:message v:R:repo '
  ['issue update']=' v:a:assignee b:c:confidential v:d:description v::due-date b:h:help v:l:label b::lock-discussion v:m:milestone b:p:public v:R:repo v:t:title b::unassign v:u:unlabel b::unlock-discussion v:w:weight '
  ['mr create']=' b::allow-collaboration v:a:assignee b::auto-merge b::copy-issue-labels b::create-source-branch v:d:description b::draft b:f:fill b::fill-commit-body v:H:head b:h:help v:l:label v:m:milestone b::no-editor b::push b::recover v:i:related-issue b::remove-source-branch v:R:repo v::reviewer b::signoff v:s:source-branch b::squash-before-merge v:b:target-branch v:t:title b:w:web b::wip b:y:yes '
  ['mr merge']=' b::auto-merge b:h:help v:m:message b:r:rebase b:d:remove-source-branch v:R:repo v::sha b:s:squash v::squash-message b:y:yes '
  ['mr note']=' b:h:help v:m:message v:R:repo b::unique '
  ['mr update']=' v:a:assignee v:d:description b::draft b:f:fill b::fill-commit-body b:h:help v:l:label b::lock-discussion v:m:milestone b:r:ready b::remove-source-branch v:R:repo v::reviewer b::squash-before-merge v::target-branch v:t:title b::unassign v:u:unlabel b::unlock-discussion b::wip b:y:yes '
  ['release create']=' v:a:assets-links b:h:help v:m:milestone v:n:name b::no-close-milestone b::no-update v:N:notes v:F:notes-file v::package-name b::publish-to-catalog v:r:ref v:D:released-at v:R:repo v:T:tag-message b::use-package-registry '
)
declare -gA LFT_ALIAS=(
  ['incident comment']='incident note'
  ['issue comment']='issue note'
  ['issue new']='issue create'
  ['mr accept']='mr merge'
  ['mr comment']='mr note'
  ['mr new']='mr create'
)
