ipc = off

preload = /home/cjpoll/Pictures/cyberpunk-main.png
#preload = /home/cjpoll/Pictures/cyberpunk-rotated.jpg

# Laptop display
wallpaper = eDP-1, /home/cjpoll/Pictures/cyberpunk-main.png

# External display (HDMI via dock, enumerates as DP-2)
wallpaper = DP-2, /home/cjpoll/Pictures/cyberpunk-main.png

# Other setups
#wallpaper = DP-3, /home/cjpoll/Pictures/cyberpunk-main.png
#wallpaper = DP-4, /home/cjpoll/Pictures/cyberpunk-main.png
#wallpaper = HDMI-A-1, /home/cjpoll/Pictures/cyberpunk-main.png
#wallpaper = HDMI-A-2, /home/cjpoll/Pictures/cyberpunk-rotated.jpg
