#! /usr/bin/env ruby

require 'git_command'
require 'net/http'
require 'json'

command :clone do |id|
  system "git clone git@github.com:#{id}"
end

command :create do |username: nil, repo_name: nil|
  str = "curl -u '#{username}' -X POST -d '{\"name\": \"#{repo_name}\"}' -H 'Content-Type: application/json' https://api.github.com/user/repos"
  puts str
  resp = `#{str}`

  resp = JSON.parse(resp)
  system "git remote add origin #{resp['ssh_url']}; git push -u origin master"
end
