#! /usr/bin/env ruby
require 'git_command'

command :clone do |repo|
  system <<-EOS
    cd ${HOME}/dev;
    git clone git@github.com:SRVentures/#{repo};
    cd #{repo};
    ln -s ${HOME}/podium/shared_project_files/#{repo}/.env .env;
    echo "**/*.swp" >> .git/info/exclude
    echo "**/*.swo" >> .git/info/exclude
  EOS
end
