#! /usr/bin/env bash

mix ecto.drop
MIX_ENV=test mix ecto.drop

mix compile --force --warnings-as-errors && \
  mix format && \
  mix credo --strict && \
  MIX_ENV=test mix ecto.drop && \
  mix test && \
  mix dialyzer
