#! /usr/bin/env bash

compose="docker compose"

if [ ! -z "${COMPOSE}" ]; then
  compose="${COMPOSE}"
fi

SERVICE="${1}";
OPTS="${*:2}"

if [ -z "${OPTS}" ]; then
	$compose run --rm "${SERVICE}" /bin/bash;
else
	$compose run --rm "${OPTS}" "${SERVICE}" /bin/bash;
fi
