#! /usr/bin/env bash

set -e;

function main()
{
  $(aws ecr get-login --registry-ids "${REGISTRY_ID}" --no-include-email)
}

PARAMS="";

while (( $# )); do
  case "${1}" in
    --registry-id)
      if [ -n "${2}"  ] && [ ${2:0:1} != "-" ]; then
        REGISTRY_ID="${2}"
        shift 2
      else
        echo "Error: Argument for ${1} is missing" >&2
        exit 1
      fi
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag ${1}" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      echo "Preserve positional Arguments"
      PARAMS="$PARAMS ${1}"
      shift
      ;;
  esac
done

if [ -z "${REGISTRY_ID}" ]; then
  echo "Error: Missing required flag --registry-id"
  exit 1
fi

eval set -- "$PARAMS"

main;
