#! /usr/bin/env bash

function main()
{
  for FILE in $(ack -l "use EctoEnum" apps/core | uniq); do
    DEST=$(echo ${FILE} | sed "s/core/shared_db/")
    echo "mkdir -p $(dirname "${DEST}") &&  cp ${FILE} ${DEST}" | bash
    echo rm $FILE
    rm $FILE
  done

  #find apps/schemas -name "*.ex" | xargs gsed -i 's/Core/Schemas/'
}

main "$@";
