#! /usr/bin/env bash

if [ -f ~/dev/surge/.tool-versions ]; then
  cp ~/dev/surge/.tool-versions ./
else
  mise trust
fi

mix deps.get && \
  mix compile --warnings-as-errors &&
  mix dialyzer --plt &&
  mix test;

