#! /usr/bin/env ruby

def main(program)
  unless program
    puts "Oh noez! You didn't say which program 😱"
    exit(1)
  end

  proj_dir = nil

  devdirs = ENV['DEVPATH']

  devdirs.split(":").each do |devdir|
    app_path = "#{devdir}/#{program}"

    if File.exist?(app_path)
      proj_dir=app_path
      break
    end
  end

  unless proj_dir
    res = `find \"${GOPATH}\" -maxdepth 3 -mindepth 3 -type d`

    res.split.each do |devdir|
      app_path = "#{devdir}/#{program}"

      if File.exist?(app_path)
        proj_dir=app_path
        break
      end
    end
  end

  unless proj_dir
    puts "🚫 🔎  Project #{program} does not exist!";
    exit 1;
  end

  sessions=`tmux list-sessions | egrep "\\b#{program}" | cut -d" " -f1 | wc -l`

  if sessions.nil? or sessions == "" or sessions.match?(/\A\s*0\n\z/)
    `tmux new-session -Add -n "Work" -c "#{proj_dir}" -s "#{program}";`
    `tmux send-keys -t "#{program}:0" "init-session #{program} #{proj_dir}" ENTER`
    `tmux switch-client -t #{program};`
  else
    `tmux switch-client -t #{program};`
  end

  exit(0)
end

program = ARGV[0]

main(program)
