#! /usr/bin/env bash

BRANCH_NAME=${1};

echo "BRANCH: ${BRANCH_NAME}"

if [ -z $(git branch --list "${BRANCH_NAME}") ]; then
	echo "A"
	git fetch origin --prune;
	clear;
	git branch -r | cut -d / -f 2 | grep ^${BRANCH_NAME}$ | xargs git checkout;
else
	echo "B"
	git fetch origin --prune && git branch -r | git checkout --track "origin/${BRANCH_NAME}"
fi

git log --graph master..HEAD;

#git diff --name-status master..HEAD | awk '{ print $2  }' | xargs -o ${EDITOR} -p
FILES=$(git diff --name-status master..HEAD | awk '{ print $2 }');

echo "Files that are different from master:";
echo "${FILES}";

for FILE in ${FILES}; do
	echo "Do you want to open ${FILE}? (y/n)";
	read ANS;
	if [[ "${ANS}" == "y" || -z "${ANS}" ]]; then
		vim "${FILE}" "+Gdiff master";
	fi
done;
