#! /usr/bin/env bash

function main()
{
	local service="${1}";

	if [ -z "${service}" ]; then
		>&2 echo "Service not specified"
		>&2 echo
		>&2 echo "Example:"
		>&2 echo
		>&2 echo "bin/rebuild fire-hydrant [--no-start]"
		>&2 echo
	fi

	docker-compose stop "${service}" &&\
		docker-compose rm -f "${service}" &&\
		docker-compose build "${service}" &&\
		startService "${@}";
}

function startService()
{
	local service="${1}";
	local args="${*:2}"

  for var in args; do
		case "${2}" in
			--no-start)
				;;
			*)
				docker-compose up -d "${service}"
				;;
		esac
  done
}

main ${*};
