#! /usr/bin/env bash

function cmd()
{
  echo
  echo -------------------
  echo "Running: $@"
  echo -------------------
  echo
  $@
}

compose="docker compose"

function main()
{
	local service="${1}";


	if [ -z "${service}" ]; then
		>&2 echo "Service not specified"
		>&2 echo
		>&2 echo "Example:"
		>&2 echo
		>&2 echo "bin/rebuild fire-hydrant [--no-start]"
		>&2 echo
	fi

	cmd ${compose} stop "${service}" &&\
		cmd ${compose} rm -f "${service}" &&\
		cmd ${compose} build "${service}" &&\
		startService "${@}";
}

function startService()
{
	local service="${1}";
	local args="${*:2}"

  for var in args; do
		case "${2}" in
			--no-start)
				;;
			*)
				cmd ${compose} up -d "${service}"
				;;
		esac
  done
}

if [ ! -z "${COMPOSE}" ]; then
  compose="${COMPOSE}"
fi

main ${*};

