#! /usr/bin/env bash

set -e

APP="${1}"
CONSUMER_GROUP="${2}"

if [ -z "${APP}" ]; then
	echo "APP not set."
	exit 1;
fi

if [ -z "${CONSUMER_GROUP}" ]; then
	echo "CONSUMER_GROUP not set."
	exit 1;
fi

#convox scale kafka --count 0 -a "${APP}";
#sleep 10;
convox run kafka-connect "kafka-consumer-groups --reset-offsets --bootstrap-server 10.1.11.11:9092 --to-earliest --all-topics --execute --group ${CONSUMER_GROUP}" -a kafka-connect-pg-docker-prod;

convox scale kafka --count 2 -a "${APP}";
