#! /usr/bin/env ruby

#HOME_IP='76.149.255.225'
HOME_IP='192.168.4.179'

REGISTERED_SERVERS = {
	"home" => {
    "office" => {
      port: 4444,
      host: "cjpoll@#{HOME_IP}",
      ports: {
        4002 => 4002,
        4003 => 4003,
        4004 => 4004,
      },
      ssh_forward: false
    },
    "laptop" => {
      port: 22,
      ports: {
        4004 => 4004
      },
      host: "cjpoll@192.168.4.190",
      ssh_forward: false
    }
  }
}

service = ARGV[0]
env = ARGV[1]

if service.nil? || env.nil?
	puts
	puts "Usage:"
	puts
	puts "shh <service> <env>"
	puts
	exit(1)
end

unless REGISTERED_SERVERS.key?(service) && REGISTERED_SERVERS[service].key?(env)
	puts
	puts "Unknown service or env"
	puts
	exit(1)
end

command = REGISTERED_SERVERS[service][env][:ports].map do |k,v|
	"-L #{k}:localhost:#{v}"
end

port = REGISTERED_SERVERS[service][env][:port]

command << REGISTERED_SERVERS[service][env][:host]
command.unshift << "-p #{port}" if port
command.unshift '-A' if REGISTERED_SERVERS[service][env][:ssh_forward]
command.unshift('ssh')

command = command.join(" ")
puts command

system command
system "ssh-kill #{service}"
