#! /usr/bin/env ruby

HOME_IP='71.195.207.146'

REGISTERED_SERVERS = {
	"home" => {
    "dev" => {
      port: 23,
      host: "cjpoll@192.168.1.139",
      ports: {
        4003 => 4003
      },
      ssh_forward: true
    }
  }
}

service = ARGV[0]
env = ARGV[1]

if service.nil? || env.nil?
	puts
	puts "Usage:"
	puts
	puts "shh <service> <env>"
	puts
	exit(1)
end

unless REGISTERED_SERVERS.key?(service) && REGISTERED_SERVERS[service].key?(env)
	puts
	puts "Unknown service or env"
	puts
	exit(1)
end

command = REGISTERED_SERVERS[service][env][:ports].map do |k,v|
	"-L #{k}:localhost:#{v}"
end

port = REGISTERED_SERVERS[service][env][:port]

command << REGISTERED_SERVERS[service][env][:host]
command.unshift << "-p #{port}" if port
command.unshift '-A' if REGISTERED_SERVERS[service][env][:ssh_forward]
command.unshift('ssh')

command = command.join(" ")
puts command

system command
system "ssh-kill #{service}"
