#! /usr/bin/env ruby

REGISTERED_SERVERS = {
  "server" => {
    "env" => {
      host: "",
      ports:  {
        9001 => 9001, # Packrat's Port
        4369 => 4369  # EPMD Port
      },
      ssh_forward: false
    },
  },
  "home" => {
    "root" => {
      host: "root@50.160.4.247",
      ports: [],
      ssh_forward: true
    },
    "terraria" => {
      host: "root@192.168.0.29",
      ports: [],
      ssh_forward: true
    }
  }
}

service = ARGV[0]
env = ARGV[1]

if service.nil? || env.nil?
  puts
  puts "Usage:"
  puts
  puts "shh <service> <env>"
  puts
  exit(1)
end

unless REGISTERED_SERVERS.key?(service) && REGISTERED_SERVERS[service].key?(env)
  puts
  puts "Unknown service or env"
  puts
  exit(1)
end

command = REGISTERED_SERVERS[service][env][:ports].map do |k,v|
  "-L #{k}:localhost:#{v}"
end

command << REGISTERED_SERVERS[service][env][:host]
command.unshift ' -A 'if REGISTERED_SERVERS[service][env][:ssh_forward]
command.unshift("ssh")

command = command.join(" ")
puts command

system command
system "ssh-kill #{service}"
