#! /usr/bin/env bash

main() {
  existing_file="${1}"
  link="${2}"

  if [ ! -f "${link}" ]; then
    ln -s "${existing_file}" "${link}"
  fi
}

printHelp() {
  echo "soft-link <existing-file> <new-link-file>"
}

if [ "${1}" == "--help" ]
then
  printHelp
else
  main "${@}"
fi
