#! /usr/bin/env bash

MOVIE="${1}";
USER="${2}";

if [ -z "${USER}" ]; then
	USER="cjpoll";
fi

case "${USER}" in
"cjpoll") DIRECTORY="/home/cjpoll/movies"
	;;
"nikki") DIRECTORY="/home/nikki/nikki_movies"
	;;
"kids") DIRECTORY="/home/nikki/kids_movies"
	;;
*)
	>&2 echo "Don't know where to put \"${USER}\"";
	exit 1;
	;;
esac


echo "scp ${MOVIE} cjpoll@192.168.0.11:${DIRECTORY};" | bash;
